// @ts-check
/* App state + persistence. Owns the mutable singletons (`state`, `activeTab`,
 * `PROJECTS`) and the localStorage cache. Sync concerns live in sync.js and
 * hook in via onSave() so this module never imports the network layer. */

import { normalize } from './store.js';

/* Data lives in localStorage: simple, synchronous, survives restarts.
 * PWA stretch goal: migrate to IndexedDB (async, bigger quota, works in
 * service workers too — needed for background sync later). */
export const STORE_KEY = 'kanban-hub-v1';

function load() {
  let s = null;
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (raw) s = JSON.parse(raw);
  } catch (e) { /* corrupted data → start fresh */ }
  return normalize(s || {});
}

/** @type {import('./store.js').BoardState} */
export let state = load();

/** Replace the whole state (used when adopting a fresher server board). */
export function setState(s) { state = s; }

export let activeTab = localStorage.getItem(STORE_KEY + ':tab') || 'all';
/** @param {string} tab */
export function setActiveTab(tab) {
  activeTab = tab;
  localStorage.setItem(STORE_KEY + ':tab', tab);
}

/* ---------- projects ---------- */

/* Projects are sourced from js/projects.json (generated by
 * scripts/gen-projects.sh from the folders in Code/). Loaded at boot. */
/** @type {import('./store.js').Project[]} */
export let PROJECTS = [];

export function projectIds() { return new Set(PROJECTS.map(p => p.id)); }
/** @param {string|null|undefined} id */
export function projectById(id) { return PROJECTS.find(p => p.id === id) || null; }

export async function loadProjects() {
  try {
    const res = await fetch('js/projects.json', { cache: 'no-cache' });
    if (res.ok) {
      const j = await res.json();
      PROJECTS = Array.isArray(j.projects) ? j.projects : [];
    }
  } catch (e) { /* offline first-load or file:// — fall back below */ }
  // Fallback: if the list couldn't load, derive it from ids already present
  // on stored tickets so existing cards still get a tab + (plain) chip.
  if (!PROJECTS.length) {
    const ids = new Set();
    Object.values(state.projects || {}).forEach(cards =>
      cards.forEach(c => { if (c.project) ids.add(c.project); }));
    PROJECTS = [...ids].map(id => ({ id, name: id, color: '#eef1fe', text: '#3b4bb8' }));
  }
}

/* ---------- persistence ---------- */

/** Cache write WITHOUT the after-save hook — used when adopting server state. */
export function writeCache() {
  cacheDirty = false;
  clearTimeout(cacheTimer);
  localStorage.setItem(STORE_KEY, JSON.stringify(state));
}

/* sync.js registers markDirty+schedulePush here. Kept as a hook (instead of
 * importing sync.js) so persistence has no dependency on the network layer
 * and store/state stay usable without a server configured. */
let afterSave = () => {};
/** @param {() => void} fn */
export function onSave(fn) { afterSave = fn; }

/** Persist synchronously to localStorage, then let sync schedule a push. */
export function save() {
  writeCache();
  afterSave();
}

/* Debounced variant for per-keystroke callers (sticky notes). The full
 * JSON.stringify of the board on every keypress is wasted work; batch the
 * cache write but still notify sync (whose push is itself debounced). */
let cacheTimer = /** @type {any} */ (null);
let cacheDirty = false;
export function saveSoon(delay = 200) {
  cacheDirty = true;
  clearTimeout(cacheTimer);
  cacheTimer = setTimeout(writeCache, delay);
  afterSave();
}

/* Don't lose a debounced write if the tab closes inside the window. */
window.addEventListener('pagehide', () => { if (cacheDirty) writeCache(); });
